version: "3.9"

name: aberdock-mp-jrd15

networks:
    aberdock_vlan:
        name: "aberdock_vlan"
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv4: "true"
        external: false
        ipam:
            driver: default
            config:
                - subnet: 11.0.0.0/16
                  gateway: 11.0.0.1

volumes:
    aberdock_mariadb:
        name: "aberdock_mariadb"

services:
    aberdock:
        build: ./AberDock_Docker
        container_name: "aberdock"
        environment:
            - MYSQL_SERVER=11.0.0.3
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=aberdock
            - MYSQL_USER=aberdock
            - MYSQL_PASSWORD=ASecurePasswordForTheAberDockAccount
        restart: unless-stopped
        networks:
            aberdock_vlan:
                ipv4_address: 11.0.0.2

    aberdock_mariadb:
        image: mariadb:latest
        container_name: "aberdock_mariadb"
        environment:
            - MYSQL_ROOT_PASSWORD=AVerySecurePassword12345678
            - MYSQL_DATABASE=aberdock
            - MYSQL_USER=aberdock
            - MYSQL_PASSWORD=ASecurePasswordForTheAberDockAccount
        volumes:
            - aberdock_mariadb:/var/lib/mysql
        restart: unless-stopped
        networks:
            aberdock_vlan:
                ipv4_address: 11.0.0.3
